# autogenerated by txs
#include:xstring
#include:leftidx
\angvel{type}{ref_frame}{frame}{coord_frame}#m
\dcm{ref_frame}{frame}#m
\pos{type}{start}{end}{coord_frame}#m
\quat{type}{ref_frame}{frame}#m
\vect{type}{symbol}{upper_left}{bottom_left}{upper_right}{bottom_right}#m
\velg{type}{ref_frame}{end}{coord_frame}#m
\vel{type}{ref_frame}{start}{end}{coord_frame}#m
\accg{type}{ref_frame}{end}{coord_frame}#m
\acc{type}{ref_frame}{start}{end}{coord_frame}#m
